services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      API_URL: ${API_URL}
      HASH_SECRET_KEY: ${HASH_SECRET_KEY}
      HASH_ALGORITHM: ${HASH_ALGORITHM}
      HASH_TOKEN_EXPIRE_MINUTES: ${HASH_TOKEN_EXPIRE_MINUTES}
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - bandit-net

  dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      API_URL: ${API_URL}
    networks:
      - bandit-net

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - bandit-net

volumes:
  db_data:

networks:
  bandit-net:
    driver: bridge
